### PR TITLE
I added a Come At Me Bro trollicon

### PR DESCRIPTION
**Pull request by patbenatar**

### CODE REVIEW

**Comment by patbenatar** [comment]
Yea its a new icon. The meme exists but no icon for it.

**Comment by bloudermilk** [comment]
+1

**Comment by GarethWalters** [comment]
+1

**Comment by jlsuttles** [comment]
+1

**Comment by ghost** [comment]
-1

**Comment by mfp4073** [comment]
+1

**Comment by patbenatar** [comment]
An alias of [comeatmebro] would probably be a good idea

**Comment by sagargp** [comment]
dude who are all these +1 krew (and the one -1)... are they always here?!

**Comment by patbenatar** [comment]
We've collectively been using the Come At Me Bro in our own build of trollicons for a while now. Would love to see this in the official release, what do you say?

**Comment by sagargp** [comment]
oh lol, okay. can you link a comic that uses this guy?

**Comment by patbenatar** [comment]
Haven't seen him in use in a comic yet, here's the description of the meme though: http://knowyourmeme.com/memes/come-at-me-bro

**Comment by rfsbraz** [comment]
I haven't seen this guy on a single comic

**Comment by sagargp** [comment]
i'm hesitant to make this pull because i haven't seen this particular guy before. i've seen the "come at me bro" meme (especially in aardvark form), but never this specific version. how about if you can make a comic that gets a significant amount of upvotes, i'll make the pull?

**Pull request closed without merging**
