### PR TITLE
Added a few more images

### PR DESCRIPTION
**Pull request by carlosefonseca**
Puke Rainbows
Homophobic Seal
If you know what i mean
Captain Obvious
Genius
I Dont Want to Live on This Planet Anymore
Picard Facepalm
WTF is this shit
Aliens

### CODE REVIEW

**Comment by carlosefonseca** [comment]
ups… some jpgs… will fix and re-add here…

**Comment by unregistered** [comment]
Awesome collection of icons!

How did you convert the jpgs to png?

**Comment by carlosefonseca** [comment]
Preview.app

**Comment by unregistered** [comment]
A conversion from a lossy format (jpg) to a lossless format (png) will still have information lost. Can you source the icons from png files instead of converting from jpg?

**Comment by paradox460** [comment]
They're rage icons. They're like 48px. I don't think a small amount of data loss is bad. 

That said, white background is no me gusta

**Comment by unregistered** [comment]
Thank you!

**Pull request merged**
