### PR TITLE
added grumpy cat

### PR DESCRIPTION
**Pull request by SyntaxStacks**
:]

### CODE REVIEW

**Comment by bwhitehead** [comment]
This should be by a black and white drawn pic, this is really out of place compared to other trollicons

**Comment by SyntaxStacks** [comment]
I recently have seen many meme-based trollicons, such as:
Stupidity - WTF is this shit
Stupidity - Picard Facepalm
Misc - Aliens

Y U NO LIKE GRUMPY CAT

**Comment by SyntaxStacks** [comment]
I can see the size being an issue

**Comment by bwhitehead** [comment]
I'm not objecting to grumpy cat, just that it is 1) an actual picture and 2) it isn't in the tradition of looking like some asshat drew it with MS Paint.

**Comment by funkytaco** [comment]
@bwhitehead So what you're saying is [nogrumpycat]? lol.

I'd like to see grumpy cat!

**Comment by bwhitehead** [comment]
Just think a photo doesn't really qualify as a icon… just find a hand drawn image like this one: http://i.imgur.com/fyPU1Nq.jpg

**Comment by sagargp** [comment]
I don't know, on the one hand I'd like to continue the tradition of crappy sketches of basic emotions; but on the other hand, the whole concept of rage faces is a mutable, ever changing tapestry of expression. I also want to avoid having way too many rarely-used icons. I'd like to get @unregistered's input on this.

**Comment by bwhitehead** [comment]
Might as well as merge in this branch, memes galore: https://github.com/rfsbraz/trollicons/commit/02b1bb1c7134340419338c46c9d3bf44822d6b59

**Comment by unregistered** [comment]
I'm inclined to agree with not merging. We have a history of being picky with the types of faces we merge in, limiting ourself to black and white / hand drawn style faces (though this policy is certainly up for discussion).

Regardless, are a number of forks of trollicons that have other memes that would better suit this icon.

**Comment by jgonz0010** [comment]
I have only ever installed this set of trollicons and to be honest this particular icon falls in line with some of the others you have. Stop trolling, and add grumpycat in.

**Comment by ruebenramirez** [comment]
I feel like I should be able to [grumpycat] here.

**Comment by funkytaco** [comment]
Heh, well I guess it's not going to get implemented now, for sure. But I'd like to point out grumpy cat is the biggest troll ever, so I don't see why it being a photo matters. None of these are even icons, not a one. You should have named it memepics, not trollicons.

**Comment by sagargp** [comment]
Ok, I'll review the icons and merge this later. By which I mean @unregistered, you should review the icons and merge this later.

**Comment by unregistered** [comment]
Ill take a look tonight

**Comment by bwhitehead** [comment]
Just want to reiterate, i'm not against grumpycat, just the 'real picture' being used. I'd love for grumpycat and other meme type stuff making it into this icon pack - just would like to see the general style stay the same: ugly black/white/red simple MS Paint looking pics.

**Comment by unregistered** [comment]
There seems to be sufficient demand for memes, we have a couple ways forward:
- Mix the two into trollicons, trolls & memes combined
- Fork trollicons into memeicons, keep the two separate 
- Have trollicons build memeicons and trollicons separately, rake build trollicons, rake build memeicons

**Comment by sagargp** [comment]
We should take advantage of the Rakefile's genericness and have it build separate packs. Basically the last option, but no change to the Rakefile. 

rake build trollicons/
rake build memeicons/

**Comment by unregistered** [comment]
After further discussion, we've decided to merge things in from now on. If and when things get crazy, we'll do something else, but it doesn't hurt to have more icons.

**Pull request merged**
