### PR TITLE
Added a new syntax that solves the [troll[ problem

### PR DESCRIPTION
**Pull request by paradox460**
So, in the past, it is a common typo to type this: `[troll[` when you meant `[troll]`.

This patch fixes 99% of this, by adding a new syntax for icons: you can now use colons. So `:troll:` is just as valid as `[troll]`

Unfortunately this doesn't work on trillian yet, because I couldn't figure out the trillian syntax, and it remains untested on all clients except for adium, as thats all I can test on.

### CODE REVIEW

**Comment by sagargp** [comment]
i think we should support a variety of input formats. so the colons is good, but also maybe the [](/bleh) format of f7u12, or at least /bleh (thought this might conflict with some plugins). also we should adopt the f7u12 naming. i was thinking of maybe parsing f7u12's stylesheet to generate our icon packs?

**Comment by paradox460** [comment]
Good luck parsing that stylesheet, its a huge mess

**Comment by sagargp** [comment]
well shit

**Comment by timdorr** [comment]
Good luck parsing a standardized format? lolwut?

**Comment by unregistered** [comment]
I think this would be good as an optional syntax in addition to the bracket syntax.  However, we can't pull this until we're sure it doesn't break something in our other supported clients.

**Comment by paradox460** [comment]
> Good luck parsing a standardized format? lolwut?

CSS is standardized, subreddit CSS is not.

**Comment by unregistered** [comment]
It's been awhile so I guess we've decided to keep the bracket syntax.

**Pull request closed without merging**
