### PR TITLE
success kid

### PR DESCRIPTION
**Pull request by apazzolini**
As seen here http://memegenerator.net/Success-Kid

### CODE REVIEW

**Comment by carlosefonseca** [comment]
Nice one! I'd just add "success" as an alias.

**Comment by apazzolini** [comment]
I don't even know how I managed to make this so complicated. Amateur hour over here.

**Comment by unregistered** [comment]
We've had a policy of not accepting meme characters, only rage faces. In accordance with this, I can't accept this commit. 

There are arguments to be made for allowing memes though, so please do start a discussion in the issues.

**Comment by apazzolini** [comment]
@unregistered are you sure you wanted to merge this? Since the pull request was closed a while ago, I just continued committing to master locally. It has quite a bit more than just adding in successkid.

If you feel it brought in too much, feel free to revert it and let me know, and I can open up a separate one with just successkid.

#42 relevant

**Comment by unregistered** [comment]
Hey @apazzolini it's good, we're accepting memes now, and we'll figure out how to organize them before the next release. If you have any other memes, be sure to submit another pull request

Thanks!

**Pull request merged**
