### PR TITLE
Memes

### PR DESCRIPTION
**Pull request by rfsbraz**
Added a couple of memes, give them a try.

### CODE REVIEW

**Comment by unregistered** [comment]
Nice.  I'll take a test drive.

**Comment by timdorr** [comment]
Merge it!

**Comment by jimmycuadra** [comment]
-1 on this. Not rage faces!

**Comment by unregistered** [comment]
It's been awhile so it seems we're rage faces only. You are welcome to maintain your own branch with other memes, though!

**Pull request closed without merging**
