### PR TITLE
Added a cat rage icon

### PR DESCRIPTION
**Pull request by paradox460**
Cat rage icon. For talking about cats and cat rages

### CODE REVIEW

**Comment by unregistered** [comment]
This is good, though I haven't seen this face used before.  I'm not sure how popular a face has to be before we add it.  I think we had a discussion on this after we added celo and the momentum died.

**Comment by paradox460** [comment]
Its one of the rarer faces, but it does show up every now and then.

**Comment by unregistered** [comment]
Can you link me to some examples on its usage?  Afaik it's not in the editors or available in f7u12 comments.

**Comment by paradox460** [comment]
Damn, i saw one the other day, but of course, i cant find it

**Comment by sagargp** [comment]
totally, i rarely see this face. one of the problems of the icon pack is that it has too many icons... i think their best use is in day to day discussion and i can't see cat rage coming up much, so i say we don't merge it. speaking of which, maybe we should prune some other rarely used faces like pigrage and even ce-lo. i wish we could get usage stats :(

**Comment by paradox460** [comment]
Well, i thought the cat would make a good counterpoint to the wetodddog.

http://www.reddit.com/tb/gs9y8
http://i.imgur.com/0DM3M.jpg
http://www.reddit.com/tb/fi9db

As for ones to cull, here are the ones i rarely use in convos, and i've got all my friends to install the comics.
Happy-hopeful
Celo
Poker face 2
Actually
Actually not ok
Stare

The others see moderately high use, with the obvious ones being highest

On Saturday, April 30, 2011 at 2:23 AM, sagargp wrote:
totally, i rarely see this face. one of the problems of the icon pack is that it has too many icons... i think their best use is in day to day discussion and i can't see cat rage coming up much, so i say we don't merge it. speaking of which, maybe we should prune some other rarely used faces like pigrage and even ce-lo. i wish we could get usage stats :(

**Comment by unregistered** [comment]
Yeah wetodddog doesn't get much use for me either.  I've used celo like once, guilty several times.  We need to develop some sort of standard on what to include in the pack. 

We can make the pack mirror the rage editor / reddit
pros: easy to manage and control
cons: doesn't have some faces we like

Alternatively we allow obscure faces
pros: we get all the faces [fy]
cons: menu clutter, obscure faces may be difficult to use correctly

**Comment by paradox460** [comment]
Kind of wish adium let you do sub-menus
On Saturday, April 30, 2011 at 2:44 AM, unregistered wrote:
Yeah wetodddog doesn't get much use for me either. I've used celo like once, guilty several times. We need to develop some sort of standard on what to include in the pack.

**Comment by sagargp** [comment]
well adium supports multiple icon packs enabled simultaneously. so we could just separate them into different packs, and enable them simultaneously... though this is pretty confusing for users who don't care that much. plus it's not the case for other IM clients.

**Comment by unregistered** [comment]
I'd rather not split multiple packs because it would make maintaining adium different from the other clients.

**Comment by paradox460** [comment]
Could use package builder to get an installer on os x, but that's still
overkill
On Apr 30, 2011 2:49 AM, "sagargp" <
reply@reply.github.com>
wrote:

**Comment by unregistered** [comment]
That actually might have to happen if we want an ichat build.

The difference between having few, safe amounts of icons and having more obscure ones is the difference between [ragebuilder](http://memebase.com/ragebuilder/) and [ragemaker](http://ragemaker.com/).

**Comment by unregistered** [comment]
Considering that most comics seem to come from ragemaker, I think we should follow their example and be open to faces.

**Pull request merged**
