### PR TITLE
Mirrored Fuck That Face

### PR DESCRIPTION
**Pull request by rfsbraz**
Added Mirrored Fuck That face, allowing the creation of awesome sequences.

### CODE REVIEW

**Comment by unregistered** [comment]
We don't have any mirrored faces yet, except for lgun and rgun.  Should we use yao2 or make this ryao, rft etc?

**Comment by rfsbraz** [comment]
I called it yao2, ft2, etc in my commit, but ryao, rft, rfuckthat, probbably makes more sense.

**Comment by unregistered** [comment]
Okay.  Can you make those changes and send another pull request?  I will close this one and pull the next one.

**Comment by sagargp** [comment]
we should have a default... so [fuckthat] is still a valid icon

**Pull request closed without merging**
